# Generated by Django 5.1.1 on 2024-10-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Bio_Data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repayment_plan",
                    models.CharField(
                        choices=[
                            ("2_months", "2 months instalment"),
                            ("5_months", "5 months instalment"),
                            ("11_months", "11 months instalment"),
                            ("17_months", "17 months instalment"),
                        ],
                        default="2_months",
                        max_length=20,
                    ),
                ),
                (
                    "down_payment_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Down payment percentage (e.g. 20.00 for 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "management_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Management fee percentage (e.g. 5.00 for 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "recurrent_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Recurrent percentage (e.g. 2.50 for 2.5%)",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutrightConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuration", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="PaygoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuration", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SalesAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code_number", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BillingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("Paygo", "Paygo (Kool Kredit)"),
                            ("Outright", "Outright"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "paygo_freezer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "repayment_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2_months", "2 months instalment"),
                            ("5_months", "5 months instalment"),
                            ("11_months", "11 months instalment"),
                            ("17_months", "17 months instalment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "monthly_instalment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "outright_freezer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bio_Data.biodata",
                    ),
                ),
                (
                    "outright_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="koolAssembly_billing_model.outrightconfig",
                    ),
                ),
                (
                    "paygo_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="koolAssembly_billing_model.paygoconfig",
                    ),
                ),
                (
                    "sales_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="koolAssembly_billing_model.salesagent",
                    ),
                ),
            ],
        ),
    ]
