# Generated by Django 5.1.1 on 2024-10-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BioData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(max_length=14)),
                (
                    "alternate_phone_number",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("street_name", models.CharField(max_length=255)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="Uganda", max_length=100)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("S", "Single"), ("M", "Married"), ("W", "Widowed")],
                        max_length=1,
                    ),
                ),
                (
                    "product_usage",
                    models.CharField(
                        choices=[("C", "Commercial"), ("D", "Domestic")], max_length=1
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("business_address", models.TextField(blank=True, null=True)),
                ("number_of_dependents", models.PositiveIntegerField(default=0)),
                ("NIN", models.CharField(max_length=20, unique=True)),
                ("occupation", models.CharField(max_length=100)),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("AD", "Advertisement"),
                            ("ER", "Employee Referral"),
                            ("FB", "Facebook"),
                            ("GS", "Google Search"),
                            ("CH", "Chat"),
                            ("WC", "Walk-in Client"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
