# Generated by Django 5.1.1 on 2024-10-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Bio_Data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smart_phone",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=3,
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                (
                    "outstanding_loan",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=3,
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("access-bank", "Access Bank"),
                            ("access-bank-diamond", "Access Bank (Diamond)"),
                            ("alat-by-wema", "ALAT by WEMA"),
                            ("asosavings", "ASO Savings and Loans"),
                            ("bowen-microfinance-bank", "Bowen Microfinance Bank"),
                            ("cemcs-microfinance-bank", "CEMCS Microfinance Bank"),
                            ("citibank-nigeria", "Citibank Nigeria"),
                            ("ecobank-nigeria", "Ecobank Nigeria"),
                            ("ekondo-microfinance-bank", "Ekondo Microfinance Bank"),
                            ("fidelity-bank", "Fidelity Bank"),
                            ("first-bank-of-nigeria", "First Bank of Nigeria"),
                            ("first-city-monument-bank", "First City Monument Bank"),
                            ("globus-bank", "Globus Bank"),
                            ("guaranty-trust-bank", "Guaranty Trust Bank"),
                            ("hasal-microfinance-bank", "Hasal Microfinance Bank"),
                            ("heritage-bank", "Heritage Bank"),
                            ("jaiz-bank", "Jaiz Bank"),
                            ("keystone-bank", "Keystone Bank"),
                            ("kuda-bank", "Kuda Bank"),
                            ("one-finance", "One Finance"),
                            ("paga", "Paga"),
                            ("parallex-bank", "Parallex Bank"),
                            ("paycom", "PayCom"),
                            ("polaris-bank", "Polaris Bank"),
                            ("providus-bank", "Providus Bank"),
                            ("rubies-mfb", "Rubies MFB"),
                            ("sparkle-microfinance-bank", "Sparkle Microfinance Bank"),
                            ("stanbic-ibtc-bank", "Stanbic IBTC Bank"),
                            ("standard-chartered-bank", "Standard Chartered Bank"),
                            ("sterling-bank", "Sterling Bank"),
                            ("suntrust-bank", "Suntrust Bank"),
                            ("taj-bank", "TAJ Bank"),
                            ("tcf-mfb", "TCF MFB"),
                            ("titan-trust-bank", "Titan Trust Bank"),
                            ("union-bank-of-nigeria", "Union Bank of Nigeria"),
                            ("united-bank-for-africa", "United Bank For Africa"),
                            ("unity-bank", "Unity Bank"),
                            ("vfd", "VFD"),
                            ("wema-bank", "Wema Bank"),
                            ("zenith-bank", "Zenith Bank"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("bank_account_name", models.CharField(max_length=255)),
                ("bvn", models.CharField(max_length=11, unique=True)),
                (
                    "other_bank_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_details",
                        to="Bio_Data.biodata",
                    ),
                ),
            ],
        ),
    ]
