# Generated by Django 5.1.1 on 2024-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account_Detail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountdetail",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("absa-bank-uganda", "Absa Bank Uganda"),
                    ("bank-of-africa-uganda", "Bank of Africa Uganda"),
                    ("bank-of-baroda-uganda", "Bank of Baroda Uganda"),
                    ("cairo-bank-uganda", "Cairo Bank Uganda"),
                    ("centenary-bank", "Centenary Bank"),
                    ("dfcu-bank", "DFCU Bank"),
                    ("diamond-trust-bank-uganda", "Diamond Trust Bank Uganda"),
                    ("equity-bank-uganda", "Equity Bank Uganda"),
                    ("exim-bank-uganda", "Exim Bank Uganda"),
                    ("finance-trust-bank", "Finance Trust Bank"),
                    ("housing-finance-bank", "Housing Finance Bank"),
                    ("kcb-bank-uganda", "KCB Bank Uganda"),
                    ("nc-bank-uganda", "NC Bank Uganda"),
                    ("postbank-uganda", "PostBank Uganda"),
                    ("stanbic-bank-uganda", "Stanbic Bank Uganda"),
                    (
                        "standard-chartered-bank-uganda",
                        "Standard Chartered Bank Uganda",
                    ),
                    ("top-finance-bank", "Top Finance Bank"),
                    ("tropical-bank", "Tropical Bank"),
                    ("uganda-development-bank", "Uganda Development Bank"),
                    ("united-bank-for-africa-uganda", "United Bank for Africa Uganda"),
                    ("abc-capital-bank", "ABC Capital Bank"),
                    ("orient-bank", "Orient Bank"),
                    ("ecobank-uganda", "Ecobank Uganda"),
                    ("guaranty-trust-bank-uganda", "Guaranty Trust Bank Uganda"),
                    ("others", "Others"),
                ],
                max_length=100,
            ),
        ),
    ]
