# Generated by Django 5.1.1 on 2024-10-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Bio_Data", "0001_initial"),
        ("koolAssembly_billing_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guarantor_fullname", models.CharField(max_length=255)),
                (
                    "guarantor_phone_number",
                    models.CharField(max_length=15, unique=True),
                ),
                ("guarantor_nin", models.CharField(max_length=11, unique=True)),
                (
                    "guarantor_nin_image",
                    models.ImageField(upload_to="guarantor_nin_images/"),
                ),
                ("reason_for_purchase", models.TextField()),
                ("referee_fullname", models.CharField(max_length=255)),
                ("referee_phone_number", models.CharField(max_length=15, unique=True)),
                ("second_referee_fullname", models.CharField(max_length=255)),
                (
                    "second_referee_phone_number",
                    models.CharField(max_length=15, unique=True),
                ),
                ("product_photo", models.ImageField(upload_to="product_photos/")),
                ("client_photo", models.ImageField(upload_to="client_photos/")),
                ("client_nin_image", models.ImageField(upload_to="client_nin_images/")),
                (
                    "bank_statements_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="bank_statements/images/"
                    ),
                ),
                (
                    "bank_statements_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="bank_statements/pdfs/"
                    ),
                ),
                (
                    "home_utility_bill_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="utility_bills/home/images/"
                    ),
                ),
                (
                    "home_utility_bill_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="utility_bills/home/pdfs/"
                    ),
                ),
                (
                    "business_utility_bill_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="utility_bills/business/images/",
                    ),
                ),
                (
                    "business_utility_bill_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="utility_bills/business/pdfs/"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_details",
                        to="Bio_Data.biodata",
                    ),
                ),
                (
                    "sales_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_details",
                        to="koolAssembly_billing_model.salesagent",
                    ),
                ),
            ],
        ),
    ]
